runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /phpinfo.php
  script: phpinfo.php

- url: /api/.*
  script: api/index.php
- url: /api
  script: api/index.php

- url: /(.+)
  script: public/\1
- url: /
  script: public/index.php

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ng2
- certs
- .git

env_variables:
  PROD_DSN: mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE
  PROD_USER: root
  PROD_PASSWORD: ''
  PRODRD_DSN: mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE
  PRODRD_USER: root
  PRODRD_PASSWORD: ''
  DEV_DSN: mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE
  DEV_USER: root
  DEV_PASSWORD: ''
